### ISSUE TITLE
buildStaticCharts function is not defined

### ISSUE THREAD

**Issue by grahamwhiteuk** [KBarrett-Powell/SUE#4]
Line 157 of `WebInterface/js/time.js` has a call to a buildStaticCharts()  function which does not exist.  This currently has the effect that the skipTime() function stops executing at line 157 and so all the window events below that line aren't attached to the map and hence the whole map stops working.  Commenting out line 157 seems to do the trick for now.

**Comment by KBarrett-Powell** [comment]
time.js has been removed in latest update, so should all be working now.
